// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using News_App.Models;

#nullable disable

namespace News_App.Migrations
{
    [DbContext(typeof(NewsContext))]
    [Migration("20250807202346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("News_App.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__category__3213E83F7F8A98C8");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("News_App.Models.Newspage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Iscreated")
                        .HasColumnType("bit")
                        .HasColumnName("iscreated");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__newspage__3213E83F23451510");

                    b.ToTable("newspage", (string)null);
                });

            modelBuilder.Entity("News_App.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Category_Id");

                    b.Property<int?>("NewspageId")
                        .HasColumnType("int")
                        .HasColumnName("Newspage_Id");

                    b.Property<string>("Post1")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("post");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__post__3213E83FD562E7D8");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NewspageId");

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("News_App.Models.Post", b =>
                {
                    b.HasOne("News_App.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__post__Category_I__5EBF139D");

                    b.HasOne("News_App.Models.Newspage", "Newspage")
                        .WithMany("Posts")
                        .HasForeignKey("NewspageId")
                        .HasConstraintName("FK__post__Newspage_I__5FB337D6");

                    b.Navigation("Category");

                    b.Navigation("Newspage");
                });

            modelBuilder.Entity("News_App.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("News_App.Models.Newspage", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
